In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_csv('Data/Customer Churn.csv')

In [3]:
df.head()

,Call Failure,Complains,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Customer Value,Churn
0,8,0,38,0,4370,71,5,17,3,1,1,30,197.640,0
1,0,0,39,0,318,5,7,4,2,1,2,25,46.035,0
2,10,0,37,0,2453,60,359,24,3,1,1,30,1536.520,0
3,10,0,38,0,4198,66,1,35,1,1,1,15,240.020,0
4,3,0,38,0,2393,58,2,33,1,1,1,15,145.805,0

In [4]:
df

,Call Failure,Complains,Subscription Length,Charge Amount,Seconds of Use,Frequency of use,Frequency of SMS,Distinct Called Numbers,Age Group,Tariff Plan,Status,Age,Customer Value,Churn
0,8,0,38,0,4370,71,5,17,3,1,1,30,197.640,0
1,0,0,39,0,318,5,7,4,2,1,2,25,46.035,0
2,10,0,37,0,2453,60,359,24,3,1,1,30,1536.520,0
3,10,0,38,0,4198,66,1,35,1,1,1,15,240.020,0
4,3,0,38,0,2393,58,2,33,1,1,1,15,145.805,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3145,21,0,19,2,6697,147,92,44,2,2,1,25,721.980,0
3146,17,0,17,1,9237,177,80,42,5,1,1,55,261.210,0
3147,13,0,18,4,3157,51,38,21,3,1,1,30,280.320,0
3148,7,0,11,2,4695,46,222,12,3,1,1,30,1077.640,0
3149,8,1,11,2,1792,25,7,9,3,1,1,30,100.680,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Call  Failure            3150 non-null   int64
 1   Complains                3150 non-null   int64
 2   Subscription  Length     3150 non-null   int64
 3   Charge  Amount           3150 non-null   int64
 4   Seconds of Use           3150 non-null   int64
 5   Frequency of use         3150 non-null   int64
 6   Frequency of SMS         3150 non-null   int64
 7   Distinct Called Numbers  3150 non-null   int64
 8   Age Group                3150 non-null   int64
 9   Tariff Plan              3150 non-null   int64
 10  Status                   3150 non-null   int64
 11  Age                      3150 non-null   int64
 12  Customer Value           3150 non-null   float64
 13  Churn                    3150 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 344.7 KB

In [6]:
df.isna().sum()

Call  Failure              0
Complains                  0
Subscription  Length       0
Charge  Amount             0
Seconds of Use             0
Frequency of use           0
Frequency of SMS           0
Distinct Called Numbers    0
Age Group                  0
Tariff Plan                0
Status                     0
Age                        0
Customer Value             0
Churn                      0
dtype: int64

In [7]:
# Separating attributes
X = df[df.columns[:13]]
# Separating label
y = df['Churn']

In [8]:
# Call StandardScaler
scaler = StandardScaler()
# Standardization of dataset values
scaler.fit(X)
X = scaler.transform(X)
print(X)

[[ 0.05122913 -0.2878304   0.63672633 ... -0.57466206 -0.11307444
  -0.52875851]
 [-1.05028466 -0.2878304   0.75338358 ...  1.74015315 -0.67934551
  -0.82203616]
 [ 0.32660758 -0.2878304   0.52006909 ... -0.57466206 -0.11307444
   2.0612852 ]
 ...
 [ 0.73967525 -0.2878304  -1.6964185  ... -0.57466206 -0.11307444
  -0.36881527]
 [-0.08646009 -0.2878304  -2.51301919 ... -0.57466206 -0.11307444
   1.17358857]
 [ 0.05122913  3.47426818 -2.51301919 ... -0.57466206 -0.11307444
  -0.71632621]]

In [9]:
# Import train_test_split
from sklearn.model_selection import train_test_split
# Separate training data and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [10]:
# Import SVM classifier
from sklearn.svm import SVC
# Create SVC object and call fit function to train model
clf = SVC()
clf.fit(X_train, y_train)

SVC()

In [11]:
# Show accuracy score
clf.score(X_test, y_test)

0.8968253968253969

In [15]:
y_pred = clf.predict(X_test)

In [21]:
#Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[514   6]
 [ 59  51]]